"""
CLIP-with-class-embeddings pretraining on CIFAR-100 @ 32x32, with zero-shot eval.

This is the fixed harness -- you do NOT edit this file. It wires together the pieces you
implement in the other modules:
    dataset.py  make_dataloaders   -> (image, label) train + test loaders
    model.py    build_model        -> image encoder + class encoder + logit_scale
    loss.py     CLIPLoss           -> symmetric contrastive objective
    eval.py     zeroshot_evaluate  -> cosine-to-class-prototype accuracy

Run:
    python train.py                 # ResNet image encoder (default)
    # edit VISION = "vit" for the CLIP Vision Transformer encoder
"""
import math
import time

import torch

from dataset import make_dataloaders
from model import build_model
from loss import CLIPLoss
from eval import zeroshot_evaluate

# ------------------------------- hyperparameters ------------------------------- #
VISION = "resnet"            # "resnet" (reuse the tour ResNet) or "vit" (CLIP ViT)
EMBED_DIM = 256              # shared image/class embedding dimension
BATCH_SIZE = 512
ONE_PER_CLASS = False        # optional task: True -> unique-class batches; also set BATCH_SIZE=64
EPOCHS = 100
WARMUP_EPOCHS = 5
BASE_LR = 1e-3               # AdamW
MIN_LR = 1e-6
WEIGHT_DECAY = 0.05         # decoupled; not applied to 1-D params (bias/norm/logit_scale)
NUM_WORKERS = 8
EVAL_EVERY = 5
NUM_CLASSES = 100
SEED = 0

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def _lr_at(epoch, epochs, warmup, base_lr, min_lr):
    if epoch < warmup:
        return base_lr * (epoch + 1) / warmup
    p = (epoch - warmup) / max(1, epochs - warmup)
    return min_lr + 0.5 * (base_lr - min_lr) * (1.0 + math.cos(math.pi * p))


def _param_groups(model, weight_decay):
    decay, no_decay = [], []
    for _, p in model.named_parameters():
        if not p.requires_grad:
            continue
        (no_decay if p.ndim <= 1 else decay).append(p)         # no wd on bias/norm/logit_scale
    return [{"params": decay, "weight_decay": weight_decay},
            {"params": no_decay, "weight_decay": 0.0}]


def main(vision=VISION, embed_dim=EMBED_DIM, batch_size=BATCH_SIZE, epochs=EPOCHS,
         warmup_epochs=WARMUP_EPOCHS, base_lr=BASE_LR, min_lr=MIN_LR,
         weight_decay=WEIGHT_DECAY, num_workers=NUM_WORKERS, eval_every=EVAL_EVERY,
         num_classes=NUM_CLASSES, one_per_class=ONE_PER_CLASS, seed=SEED):
    torch.manual_seed(seed)
    if DEVICE.type == "cuda":
        torch.backends.cudnn.benchmark = True

    train_loader, test_loader = make_dataloaders(batch_size, num_workers=num_workers,
                                                 one_per_class=one_per_class)
    model = build_model(vision=vision, embed_dim=embed_dim, num_classes=num_classes).to(DEVICE)
    criterion = CLIPLoss()
    optimizer = torch.optim.AdamW(_param_groups(model, weight_decay), lr=base_lr, betas=(0.9, 0.98))

    print(f"CLIP pretrain: vision={vision} on CIFAR-100 32x32 | batch {batch_size} "
          f"| one_per_class={one_per_class} | {epochs} epochs | embed_dim {embed_dim} | device {DEVICE}")

    for epoch in range(epochs):
        model.train()
        lr = _lr_at(epoch, epochs, warmup_epochs, base_lr, min_lr)
        for g in optimizer.param_groups:
            g["lr"] = lr

        t0 = time.time()
        loss_sum, n_steps = 0.0, 0
        for images, labels in train_loader:
            images = images.to(DEVICE, non_blocking=True)
            labels = labels.to(DEVICE, non_blocking=True)
            image_emb, class_emb = model(images, labels)
            loss = criterion(image_emb, class_emb, labels, model.logit_scale)

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            optimizer.step()
            loss_sum += loss.item()
            n_steps += 1

        msg = (f"epoch {epoch:3d} | lr {lr:.4f} | loss {loss_sum / max(1, n_steps):.4f} "
               f"| {time.time() - t0:.1f}s")
        if (epoch + 1) % eval_every == 0 or epoch == epochs - 1:
            acc = zeroshot_evaluate(model, test_loader, num_classes, DEVICE)
            msg += f" | zero-shot top-1 {acc:.2f}%"
        print(msg, flush=True)

    return model


if __name__ == "__main__":
    main()
