"""
SimCLR pretraining on CIFAR-100 @ 32x32, with a kNN monitor.

This is the fixed harness -- you do NOT edit this file. It wires together the pieces you
implement in the other modules:
    dataset.py  make_dataloaders  -> contrastive pairs + kNN loaders
    model.py    build_model       -> encoder f(.) + projection head g(.)
    loss.py     NTXentLoss        -> the contrastive objective
    eval.py     knn_evaluate      -> representation quality monitor

Run:
    python train.py
"""
import math
import time

import torch

from dataset import make_dataloaders
from model import build_model
from loss import NTXentLoss
from eval import knn_evaluate

# ------------------------------- hyperparameters ------------------------------- #
ARCH = "resnet18"
PROJ_DIM = 128
TEMPERATURE = 0.5             # NT-Xent temperature (tau); 0.5 works well on CIFAR
BATCH_SIZE = 512
EPOCHS = 200
WARMUP_EPOCHS = 10
BASE_LR = 0.6                 # SGD, linear scaling 0.3 * BATCH_SIZE / 256
MIN_LR = 1e-3
MOMENTUM = 0.9
WEIGHT_DECAY = 1e-4
NUM_WORKERS = 8
KNN_K = 200
KNN_T = 0.1
EVAL_EVERY = 10              # run the kNN monitor every this many epochs
NUM_CLASSES = 100
SEED = 0

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def _lr_at(epoch, epochs, warmup, base_lr, min_lr):
    if epoch < warmup:
        return base_lr * (epoch + 1) / warmup                  # linear warmup
    p = (epoch - warmup) / max(1, epochs - warmup)
    return min_lr + 0.5 * (base_lr - min_lr) * (1.0 + math.cos(math.pi * p))   # cosine decay


def main(arch=ARCH, proj_dim=PROJ_DIM, temperature=TEMPERATURE, batch_size=BATCH_SIZE,
         epochs=EPOCHS, warmup_epochs=WARMUP_EPOCHS, base_lr=BASE_LR, min_lr=MIN_LR,
         momentum=MOMENTUM, weight_decay=WEIGHT_DECAY, num_workers=NUM_WORKERS,
         knn_k=KNN_K, knn_t=KNN_T, eval_every=EVAL_EVERY, num_classes=NUM_CLASSES, seed=SEED):
    torch.manual_seed(seed)
    if DEVICE.type == "cuda":
        torch.backends.cudnn.benchmark = True

    contrastive_loader, memory_loader, test_loader = make_dataloaders(
        batch_size, num_workers=num_workers)
    model = build_model(arch=arch, proj_dim=proj_dim).to(DEVICE)
    criterion = NTXentLoss(temperature=temperature)
    optimizer = torch.optim.SGD(model.parameters(), lr=base_lr, momentum=momentum,
                                weight_decay=weight_decay, nesterov=True)

    print(f"SimCLR pretrain: {arch} on CIFAR-100 32x32 | batch {batch_size} | "
          f"{epochs} epochs | tau {temperature} | device {DEVICE}")

    for epoch in range(epochs):
        model.train()
        lr = _lr_at(epoch, epochs, warmup_epochs, base_lr, min_lr)
        for g in optimizer.param_groups:
            g["lr"] = lr

        t0 = time.time()
        loss_sum, n_steps = 0.0, 0
        for (v1, v2), _ in contrastive_loader:
            v1 = v1.to(DEVICE, non_blocking=True)
            v2 = v2.to(DEVICE, non_blocking=True)
            z1, z2 = model(v1), model(v2)
            loss = criterion(z1, z2)

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            optimizer.step()
            loss_sum += loss.item()
            n_steps += 1

        msg = (f"epoch {epoch:3d} | lr {lr:.4f} | loss {loss_sum / max(1, n_steps):.4f} "
               f"| {time.time() - t0:.1f}s")
        if (epoch + 1) % eval_every == 0 or epoch == epochs - 1:
            acc = knn_evaluate(model, memory_loader, test_loader, DEVICE,
                               k=knn_k, temperature=knn_t, num_classes=num_classes)
            msg += f" | kNN top-1 {acc:.2f}%"
        print(msg, flush=True)

    return model


if __name__ == "__main__":
    main()
